# Generated by Django 2.1.7 on 2019-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash'), ('qiwi', 'qiwi')], default='card', max_length=10),
        ),
    ]
