# Generated by Django 2.1.7 on 2019-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0010_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
